theme: jekyll-theme-slate
html { 
  background: url(https://img.purch.com/rc/1280x800/aHR0cDovL3d3dy5zcGFjZS5jb20vaW1hZ2VzL2kvMDAwLzA0MC82OTgvb3JpZ2luYWwvZGVlcC1zcGFjZS1sYS1zaWxsYS0xOTIwLmpwZw==) no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  }
